# Generated by Django 3.1.3 on 2021-01-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
