# Generated by Django 3.1.3 on 2021-01-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_my_description_my_prise_my_subtitle_my_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('genre', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('year', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='my_description',
        ),
        migrations.DeleteModel(
            name='my_prise',
        ),
        migrations.DeleteModel(
            name='my_subtitle',
        ),
        migrations.DeleteModel(
            name='my_title',
        ),
    ]
